exclude_paths:
 - ".phpcs/**/*"
 - "tests/**/*"
engines:
  phpmd:
    enabled: false
    config:
      file_extensions: "php"
      rulesets: "unusedcode"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "/code/.phpcs/Barracuda/ruleset.xml"
      ignore_warnings: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**/*.php"
